image: docker.lmx.su/build/docker:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker build -t 19stefan98/tests:latest .
    - docker push 19stefan98/tests:latest
  tags:
    - docker-build
  only:
    - master

test:
  stage: test
  variables:
    ALLURE_RES: /builds/$CI_PROJECT_PATH/$ALLURE_FOLDER
  before_script:
    - apk add --update openssh-client bash
    - mkdir -p "$ALLURE_RES"
  script:
    - docker stop tests_pom || true && docker rm tests_pom || true
    - docker run -e TEST_HOST=$TEST_HOST -e ALLURE_FOLDER=$ALLURE_FOLDER --name tests_pom 19stefan98/tests:latest
  after_script:
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$SSH_RUNNER_KEY")'
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-keyscan lmx@10.0.0.42
    - docker cp tests:/$VERSION .
    - ls "$ALLURE_RES"
    - scp -r "$ALLURE_RES" lmx@10.0.0.42:~/
  artifacts:
    paths:
      - $ALLURE_FOLDER
    expire_in: 1 days
  tags:
    - docker-build
  only:
    - master
